In [17]:
# %%sql -r dataframe_1
# USE SCHEMA DEMO_DB.UTIL_SCH;

In [29]:
import os
from pathlib import Path
import pandas as pd
import numpy as np

In [30]:
print("Current working dir :- " + os.getcwd())
BASE_DIR = Path().resolve().parent
# For notebooks, use: BASE_DIR = Path().resolve()
# For files, use: BASE_DIR = Path(__file__).resolve().parent
coffee_path = BASE_DIR / "warmup-data" / "coffee.csv"
print('Base Dir :- ' + str(BASE_DIR))
print('File Path :- ' + str(coffee_path))

Current working dir :- /Users/pavanteja/data_engineering/python_vs/pandas/complete-pandas-tutorial/my_work
Base Dir :- /Users/pavanteja/data_engineering/python_vs/pandas/complete-pandas-tutorial
File Path :- /Users/pavanteja/data_engineering/python_vs/pandas/complete-pandas-tutorial/warmup-data/coffee.csv

In [82]:
coffee = pd.read_csv(coffee_path)

In [ ]:
coffee['price'] = 4.99

In [ ]:
coffee.columns

In [ ]:
coffee["new_price"] = np.where(coffee["Coffee Type"] == 'Latte',5.99, 3.99)

In [ ]:
# coffee = coffee.drop(columns = ("price"))
coffee = coffee.rename(columns = {'new_price':'price'})

In [ ]:
coffee['revenue'] = coffee['Units Sold'] * coffee['price']
coffee

In [83]:
coffee.loc[[2,3],'Units Sold'] = np.nan

In [84]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [85]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate().round(0)

In [86]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
2     Tuesday    Espresso        22.0
3     Tuesday       Latte        28.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [81]:
coffee['Units Sold'] = coffee['Units Sold'].fillna(coffee['Units Sold'].mean())

In [80]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        15.0
2     Tuesday    Espresso         NaN
3     Tuesday       Latte         NaN
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0