In [23]:
import os
from pathlib import Path
import pandas as pd
import numpy as np

In [24]:
print('current dir :- ' + os.getcwd())
base_dir = Path().resolve().parent
bios_file_path = base_dir / "data/bios.csv"
print('base dir :- '+ str(base_dir))
print('base dir :- '+ str(bios_file_path))

current dir :- /Users/pavanteja/data_engineering/python_vs/pandas/complete-pandas-tutorial/my_work
base dir :- /Users/pavanteja/data_engineering/python_vs/pandas/complete-pandas-tutorial
base dir :- /Users/pavanteja/data_engineering/python_vs/pandas/complete-pandas-tutorial/data/bios.csv

In [87]:
bios = pd.read_csv(bios_file_path)

In [27]:
bios.columns

Index(['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
       'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date'],
      dtype='str')

In [28]:
bios[bios['name'].str.contains("pavan",case=False)].head(1)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
30305,30537,Camillo Pavanello,1879-10-20,Terni,Terni,ITA,Italy,NaN,NaN,1951-07-07

In [29]:
bios['born_date'] = pd.to_datetime(bios['born_date'])

In [30]:
bios['born_date'].dt.day

0         12.0
1          1.0
2         13.0
3         11.0
4         17.0
          ...
145495    30.0
145496    20.0
145497     8.0
145498    19.0
145499    15.0
Name: born_date, Length: 145500, dtype: float64

In [31]:
bios_new = bios.copy()

In [32]:
bios_new["first_name"] = bios_new['name'].str.split(" ").str[0]

In [33]:
bios_new["last_name"] = bios_new['name'].str.split(" ").str[1:].str.join(" ")

In [34]:
bios_new[["name","first_name","last_name"]].head()

                    name     first_name last_name
0  Jean-François Blanchy  Jean-François   Blanchy
1         Arnaud Boetsch         Arnaud   Boetsch
2           Jean Borotra           Jean   Borotra
3        Jacques Brugnon        Jacques   Brugnon
4           Albert Canet         Albert     Canet

In [35]:
bios_new["born_year"]= bios_new["born_date"].dt.year
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,last_name,born_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Blanchy,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Boetsch,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Borotra,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Brugnon,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Canet,1878.0

In [37]:

bios_new.to_csv(f'{base_dir}/my_work/saved_csv/bios_new.csv', index=False)

In [45]:
bios_new["height_cat"] = bios_new["height_cm"].apply(lambda x: 'missing' if pd.isna(x) else('short' if x < 160.0 else('avrage' if x < 200 else 'tall')))

In [48]:
bios_new.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,last_name,born_year,height_cat
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Blanchy,1886.0,missing
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Boetsch,1969.0,avrage

In [56]:
def cat_hight_weight(row):
    if pd.isna(row['height_cm']) | pd.isna(row['weight_kg']):
        return 'missing values'
    elif row['height_cm'] < 175.0 and row['weight_kg'] < 70.0:
        return 'Light weight'
    elif row['height_cm'] < 200.0 or row['weight_kg'] < 95.0:
        return 'medium weight'
    else:
        return 'Heavy weight'

In [58]:
bios_new["height_cat_weigh"] = bios_new.apply(cat_hight_weight, axis=1)
bios_new.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,last_name,born_year,height_cat,height_cat_weigh
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Blanchy,1886.0,missing,missing values
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Boetsch,1969.0,avrage,medium weight

In [60]:
noc_regions = pd.read_csv(f'{base_dir}/data/noc_regions.csv')

In [61]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [67]:
# pd.merge(bios_new, noc_regions, left_on="born_country", right_on="NOC")
bios_new["born_country_name"] = pd.merge(bios_new, noc_regions, left_on="born_country", right_on="NOC",how="left")[["region"]]

In [68]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,last_name,born_year,height_cat,height_cat_weigh,born_country_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,Blanchy,1886.0,missing,missing values,France
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,Boetsch,1969.0,avrage,medium weight,France
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,Borotra,1898.0,avrage,medium weight,France
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,Brugnon,1895.0,avrage,Light weight,France
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,Canet,1878.0,missing,missing values,UK

In [79]:
usa = bios_new[bios_new['born_country']=='USA'].copy()
gbr = bios_new[bios_new['born_country']=='GBR'].copy()

In [86]:
new_df = pd.concat([usa,gbr])
new_df['born_country'].unique()

<StringArray>
['USA', 'GBR']
Length: 2, dtype: str